### PR TITLE
Added merge_lines argument and function.

### PR DESCRIPTION
**Pull request by paulcbauer**
I added a merge_lines argument in the bib2df() function and the underlying bib2df_merge_lines() function.

### CODE REVIEW

**Comment by mschilli87** [comment]
@giabaio: Did you close this on purpose or accidentally when deleting/renaming the `master` branch?

**Comment by giabaio** [comment]
No - sorry. I think it's the renaming of the branch that closed this...

**Comment by mschilli87** [comment]
AFAIK, with your new admin powers you should able to change the target branch of the PR to `main` and re-open it.

**Comment by giabaio** [comment]
@paulcbauer Can you please resend the PR to `main` (instead of the now defunct `master`)? I am not sure I can redirect to a defunct branch?...

**Comment by mschilli87** [comment]
@giabaio: Have you tried [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)?

**Comment by giabaio** [comment]
Yep --- but there's no option to change the branch. Let me quickly try something, though (then I'll have to do something else and may come back to this later...)

**Comment by giabaio** [comment]
@maelle: done. I have temporarily reopened the `master` branch, re-based the PR and then deleted `master` - but this PR will remain live and open because it now points to `main`. I'll check that it works and see if I can merge.

**Comment by paulcbauer** [comment]
All good or should I resend the PR?

**Comment by giabaio** [comment]
No --- all good thanks!

---

Gianluca Baio
Professor of Statistics and Health Economics | Head of Department


Department of Statistical Science | University College London
1-19 Torrington Place, London, WC1E 6BT, UK
Twitter: @stats_ucl<https://twitter.com/stats_UCL> | Instagram: @stats_UCL<https://instagram.com/ucl.stats/>


Telephone: +44(0)20 7679 1248 (internal: 41248)
Website: http://www.homepages.ucl.ac.uk/~ucakgba
Blog: https://gianluca.statistica.it/blog/
Book a meeting with me: https://book.morgen.so/gianlucabaio/book-me


***@***.***>   [https://www.svgrepo.com/show/157815/twitter.svg] <https://twitter.com/gianlubaio>    [https://www.svgrepo.com/show/138936/linkedin.svg] <https://www.linkedin.com/in/gianluca-baio-b893879/>    [https://www.svgrepo.com/show/341847/github.svg] <https://github.com/giabaio>    [https://www.geol.umd.edu/styles/academicons-192/svg/arxiv.svg] <https://arxiv.org/a/baio_g_1.html>    [https://www.geol.umd.edu/styles/academicons-192/svg/orcid.svg] <https://orcid.org/0000-0003-4314-2570>    [https://www.svgrepo.com/show/40973/soundcloud.svg] <https://soundcloud.com/uclsound/sets/sample-space>

_____________________________________________

For Head of Department correspondence, please use ***@***.******@***.***>

[https://s1g.s3.amazonaws.com/3f32ef1962be41fb8943ee58d28cf3aa.png]

This email may reach you outside of your working hours. If that’s the case, please do not feel pressure to reply immediately.
________________________________

**Pull request merged**
